# Generated by Django 4.2.25 on 2025-10-15 20:16

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('moroso', 'Moroso')], default='activo', max_length=10)),
                ('score_crediticio', models.IntegerField(default=500)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('anual', 'Anual')], max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_prestamos', models.IntegerField(default=0)),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('pagos_recibidos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('mora_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_interes', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('plazo_meses', models.IntegerField()),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('personal', 'Personal'), ('comercial', 'Comercial'), ('emergencia', 'Emergencia')], default='personal', max_length=15)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('activo', 'Activo'), ('completado', 'Completado'), ('vencido', 'Vencido')], default='pendiente', max_length=15)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('garantia', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='microcreditos.cliente')),
            ],
            options={
                'verbose_name_plural': 'Préstamos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('vencido', 'Vencido'), ('parcial', 'Parcial')], default='pendiente', max_length=15)),
                ('mora', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='microcreditos.prestamo')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
                'ordering': ['numero_cuota'],
            },
        ),
    ]
