# Generated by Django 4.2.20 on 2025-10-15 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('microcreditos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteMensajeInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('nota', 'Nota General'), ('seguimiento', 'Seguimiento'), ('incidencia', 'Incidencia'), ('recordatorio', 'Recordatorio'), ('evaluacion', 'Evaluación Crediticia'), ('contacto', 'Contacto Cliente')], default='nota', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('es_privado', models.BooleanField(default=False)),
                ('fecha_seguimiento', models.DateTimeField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_internos', to='microcreditos.cliente')),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_completados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mensajes Internos de Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ClienteAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('cedula', 'Cédula de Identidad'), ('comprobante_ingresos', 'Comprobante de Ingresos'), ('referencias_comerciales', 'Referencias Comerciales'), ('referencias_personales', 'Referencias Personales'), ('contrato', 'Contrato'), ('garantia', 'Garantía'), ('otros', 'Otros Documentos')], default='otros', max_length=30)),
                ('archivo', models.FileField(upload_to='clientes/adjuntos/%Y/%m/%d/')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('es_confidencial', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='microcreditos.cliente')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Adjuntos de Clientes',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
