# Generated by Django 4.2.20 on 2025-10-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microcreditos', '0002_clientemensajeinterno_clienteadjunto'),
    ]

    operations = [
    ]
