# Generated by Django 4.2.20 on 2025-10-15 21:33

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('microcreditos', '0003_auto_20251015_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración Principal', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de esta configuración de crédito')),
                ('interes_anual', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Tasa de interés anual en porcentaje (ej: 15.00 para 15%)', max_digits=5)),
                ('numero_periodos_defecto', models.IntegerField(default=12, help_text='Número de períodos (cuotas) por defecto para nuevos préstamos')),
                ('pagos_extra_permitidos', models.BooleanField(default=True, help_text='Permitir pagos adicionales al monto de la cuota')),
                ('tipo_calculo', models.CharField(choices=[('estandar', 'Estándar'), ('frances', 'Francés'), ('aleman', 'Alemán'), ('americano', 'Americano')], default='estandar', help_text='Método de cálculo de cuotas', max_length=20)),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Monto mínimo de préstamo', max_digits=10)),
                ('monto_maximo', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), help_text='Monto máximo de préstamo', max_digits=10)),
                ('periodos_minimos', models.IntegerField(default=1, help_text='Número mínimo de períodos (cuotas)')),
                ('periodos_maximos', models.IntegerField(default=60, help_text='Número máximo de períodos (cuotas)')),
                ('comision_apertura', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Comisión de apertura en porcentaje', max_digits=5)),
                ('gastos_administrativos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gastos administrativos fijos', max_digits=8)),
                ('activa', models.BooleanField(default=True, help_text='Configuración activa en el sistema')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_credito', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Crédito',
                'verbose_name_plural': 'Configuraciones de Crédito',
                'ordering': ['-activa', '-fecha_modificacion'],
            },
        ),
    ]
