# Generated by Django 4.2.20 on 2025-10-15 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microcreditos', '0004_configuracioncredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='configuracion_credito',
            field=models.ForeignKey(blank=True, help_text='Configuración de crédito utilizada', null=True, on_delete=django.db.models.deletion.PROTECT, to='microcreditos.configuracioncredito'),
        ),
    ]
