# Generated by Django 4.2.20 on 2025-10-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcreditos', '0005_prestamo_configuracion_credito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del diario')),
                ('codigo', models.CharField(help_text='Código único del diario', max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el diario está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diario',
                'verbose_name_plural': 'Diarios',
                'ordering': ['codigo', 'nombre'],
            },
        ),
    ]
