# Generated by Django 4.2.20 on 2025-10-15 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('microcreditos', '0006_diario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePagoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microcreditos.pago')),
            ],
            options={
                'verbose_name': 'Detalle Pago-Cuota',
                'verbose_name_plural': 'Detalles Pago-Cuota',
            },
        ),
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to='microcreditos.cliente')),
                ('cuotas_pagadas', models.ManyToManyField(through='microcreditos.DetallePagoCuota', to='microcreditos.pago')),
                ('diario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_pago', to='microcreditos.diario')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_pago', to='microcreditos.prestamo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Pago',
                'verbose_name_plural': 'Registros de Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.AddField(
            model_name='detallepagocuota',
            name='registro_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microcreditos.registropago'),
        ),
        migrations.AlterUniqueTogether(
            name='detallepagocuota',
            unique_together={('registro_pago', 'cuota')},
        ),
    ]
