# Generated by Django 4.2.20 on 2025-10-15 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microcreditos', '0007_detallepagocuota_registropago_and_more'),
    ]

    operations = [
    ]
